api:
  name: "s-socialMedia-fb-api"
  port: "8084"
  
facebook:
  page_id: "![utbmeoDUXCR7dlqISzg2hg==]"
  page_name: "![HyD3E48ayz/m82Po7PIEwA==]"
  access_token: "![hLSZ2Ut/Eq/XBKy2nBt0ZeGhVdkNazfCdkf70kGOecZyKPu+D9MpVS97QvlHJR22dVBDSMln7rNAaDPRiyGaPTqOVDiRNa0z07guz+uw3jHll0ONx0nVr6B4haxGyv4IYZiRVQXlhrcTGKhYIppfXE87q/HJkyWGN5DuCHJldMsZ9aojwFNLydPymZp+qW+a/V0NypFEoiQ8U9YUv+7eZ9TuV7OeOoOxi1KygZ6DPol+Y7NjKS0Hyi785koTbu2JEyfyozfcnvWac6A5HXE+WQ==]"
  access_token_page: "![hLSZ2Ut/Eq/V5n0Pfwql/41+QotYLkts4XlZZqF59kgYL2VG0Tx0y4HbhokPD15leWoZD31MobuvUUBh2lccvmu3S7jBJstqvt2AhLudZd1oj7nSL1ADCArwgpmcneXwQjFbSGxwuQ0/vRc2E+tuNdfFEygIIrXcECuZtfSPZtRUG0t3JeSGmnBw6SYOXpqilQQhj11vwiUpZ0/OPsIFXf2JfcnuoPcEIL8LqyZW8mA1kABchmadhEOga+QKxJrfai6IuealOkINzCblcZHjmkTxYhqCDpFV9ns6zUtFA7n1dntXTnKlFg==]"